export type AlbumType = {
  wrapperType: "collection";
  collectionType: "Album";
  artistId: number;
  collectionId: number;
  amgArtistId?: number;
  artistName: string;
  collectionName: string;
  collectionCensoredName: string;
  artistViewUrl: string;
  collectionViewUrl: string;
  artworkUrl60: string;
  artworkUrl100: string;
  collectionPrice?: number;
  collectionExplicitness: "notExplicit" | "explicit" | "cleaned";
  contentAdvisoryRating?: "Clean" | string;
  trackCount: number;
  copyright?: string;
  country: string;
  currency: string;
  releaseDate: string;
  primaryGenreName: string;
};